#cloud-config
users:
  - name: cybozu
    sudo: ALL=(ALL) NOPASSWD:ALL
    primary-group: cybozu
    groups: users, admin
    lock_passwd: false
    passwd: $6$rounds=4096$m3AVOWeB$EPystoHozf.eJNCm4tWyRHpJzgTDymYuGOONWxRN8uk4amLvxwB4Pc7.tEkZdeXewoVEBEX5ujUon9wSpEf1N.
