version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1-stretch
    working_directory: /go/src/github.com/cybozu-go/placemat-menu
    steps:
      - checkout
      - run: go get -u github.com/coreos/ignition/validate
      - run: go get -u github.com/google/go-jsonnet
      - run: go get github.com/golang/lint/golint
      - run: go get golang.org/x/tools/cmd/goimports
      - run: (! $GOPATH/bin/goimports -d . 2>&1 | read _)
      - run: test $($GOPATH/bin/golint ./... | grep -v "returns unexported type" | wc -l) -eq 0
      - run: go get -v -t -d ./...
      - run: go test -race -v ./...
